Back button to end of service report view
ministryofjustice/hmpps-interventions-ui pull request #1444
Opened 2022-05-12 10:22 UTC by markmoj

## What does this pull request do?

Adds back button to service-provider/end-of-service-report to successfully navigate to the previous page

## What is the intent behind these changes?
to solve bug (https://trello.com/c/0k21mW9b/305-%F0%9F%90%9Bpages-missing-back-button)

2022-05-12 13:20 UTC, NeilLuptonMoJ requested changes
* back link needs to work for PP users as well
* can you squash the commits, so the PR only has a single commit

2022-05-12 13:20 UTC, NeilLuptonMoJ commented on server/routes/shared/endOfServiceReport/endOfServiceReportPresenter.ts
> +  readonly hrefBackLink = `/service-provider/referrals/${this.endOfServiceReport.referralId}/progress`
End of service report can be viewed by probation practitioner as well, this gives them a link back to a page they can't view

2022-05-12 14:38 UTC, markmoj commented
Hi David, I've provided the fix for pp. How do I mesh all the commits?

2022-05-13 08:27 UTC, markmoj commented on server/routes/shared/endOfServiceReport/endOfServiceReportPresenter.ts
> +    : `/probation-practitioner/referrals/${this.endOfServiceReport.referralId}/progress`
I've applied these changes. see latest commit

2022-05-13 10:45 UTC, NeilLuptonMoJ reviewed
Looks good, can you rebase the change to squash the commits down to one  (`git rebase -i main` to run an interactive rebase)

2022-05-13 11:54 UTC, markmoj commented
Not sure if I have managed to rebase correctly

2022-05-16 09:13 UTC, NeilLuptonMoJ approved these changes

2022-05-16 09:17 UTC, merged