this commit changes the token used to access the interventions API
ministryofjustice/hmpps-interventions-ui pull request #43
Opened 2020-12-11 08:55 UTC by tomsmyers

## What does this pull request do?

instead of using the client_credentials token for the interventions service calls, use the logged in user's token, which provides username details and roles to the downstream service.

## What is the intent behind these changes?

 this allows granular role management and user-authenticated HMPPS Auth API calls at the API layer. it also allows the interventions API to associate calls with logged in users.

2020-12-11 09:34 UTC, sldblog commented
Would this allow every user API access to the backend without the UI?

2020-12-11 12:50 UTC, sldblog commented
Summarising an "off github" discussion: I misunderstood what this does :)

2020-12-11 12:52 UTC, sldblog reviewed
Summarising an "off github" discussion: I misunderstood what this does :)

LGTM, but would like to defer approval to @Gweaton and @lawrence-forooghian

2020-12-14 08:10 UTC, lawrence-forooghian requested changes

2020-12-14 08:10 UTC, lawrence-forooghian commented on server/services/interventionsService.ts
> +  private async createRestClient(token: string): Promise<RestClient> {
I think it's a bit confusing for this to remain `async` - can we remove that?

2020-12-14 11:10 UTC, lawrence-forooghian approved these changes

2020-12-14 11:12 UTC, merged