Ic-1833 consistent url
ministryofjustice/hmpps-interventions-ui pull request #798
Opened 2021-09-10 09:01 UTC by rgforsyth

## What does this pull request do?

Updates the pp post-session-feedback url to be consistent with the others.

## What is the intent behind these changes?

All other url's are in the form `probation-practitioner/referral/:id/...` . This change is to bring the pp-post-session-feedback url in line as it was the only one not following this form.

Old: `probation-practitioner/:actionPlanId/appointment/:sessionNumber/post-session-feedback`
New: `probation-practitioner/referrals/:referralId/appointment/:sessionNumber/post-session-feedback`

2021-09-10 10:19 UTC, Gweaton reviewed
Nice - would you mind squashing the two commits together? They essentially have the same commit message and the first one introduces the method for getting a session that's later removed, so makes sense to take it out.

2021-09-10 10:45 UTC, Gweaton approved these changes
Thanks for squashing!

2021-09-15 09:23 UTC, sldblog commented
📝 From deploy huddle: we should figure out how to handle the old URLs after this change

2021-09-15 14:12 UTC, Gweaton requested changes
Dismissing my last review to stop us merging by mistake as I didn't consider on the backwards compatibility side of this

2021-09-20 09:04 UTC, Gweaton commented
Closing this in favour of https://github.com/ministryofjustice/hmpps-interventions-ui/pull/830 which leaves the old routes in.

2021-09-20 09:04 UTC, closed without merging